/**
 * =============================================================================
 * InnovateX Revenue OS — Cal.com Settings Model
 * =============================================================================
 *
 * FILE: src/modules/bookings/calcomSettings.model.js
 *
 * Genuinely separate from calendlySettings.model.js (an existing, real,
 * but currently unbridged Calendly integration) -- this file is not
 * touched by this work at all, per instruction not to modify unrelated
 * modules. Cal.com is a new, independent integration.
 *
 * SECURITY: apiKey and webhookSecret are stored using this codebase's
 * real AES-256-GCM encrypt()/decrypt() utility (src/utils/crypto.js) --
 * the same genuinely reversible encryption already proven for Google
 * Ads' refresh token, not the strip-from-response-only treatment used
 * for the simpler WhatsApp/Meta Ads API-key providers. Requested
 * explicitly for this integration, honored precisely.
 *
 * SOURCE: real Cal.com API v2 docs (cal.com/docs/api-reference/v2) --
 * confirmed API-key auth via `Authorization: Bearer cal_live_...` (not
 * OAuth -- OAuth is a separate, more complex "Platform" tier for managed
 * sub-users, not what a normal tenant's own Cal.com account has access
 * to), confirmed real webhook creation/signature model.
 * =============================================================================
 */

import mongoose from 'mongoose';

const { Schema } = mongoose;

const calcomSettingsSchema = new Schema(
  {
    tenantId: {
      type:     Schema.Types.ObjectId,
      ref:      'Tenant',
      required: true,
      unique:   true,
      index:    true,
    },

    // ── Credentials (encrypted at rest) ──────────────────────────────────────
    apiKey:         { type: String, default: null }, // encrypted -- real Cal.com API key, format cal_live_...
    webhookSecret:  { type: String, default: null }, // encrypted -- generated by this app, given to Cal.com on webhook creation, used to verify X-Cal-Signature-256

    // ── Real Cal.com webhook subscription, created via their API ────────────
    webhookId:      { type: String, default: null },
    webhookUrl:     { type: String, default: null },

    // ── Connection state ──────────────────────────────────────────────────
    connected:      { type: Boolean, default: false },
    connectedAt:    { type: Date, default: null },
    lastVerifiedAt: { type: Date, default: null },
    lastSyncedAt:   { type: Date, default: null },
    lastSyncError:  { type: String, default: null },

    // Real account context, fetched on connect for a friendlier UI --
    // Cal.com's /v2/me endpoint returns the authenticated user's own
    // username/email tied to this API key.
    accountEmail:   { type: String, default: '' },
    accountUsername: { type: String, default: '' },

    updatedBy: {
      type: Schema.Types.ObjectId,
      ref:  'User',
      default: null,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform(doc, ret) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
        // Real secrets never leave the server, even encrypted.
        ret.hasApiKey = !!ret.apiKey;
        delete ret.apiKey;
        delete ret.webhookSecret;
        return ret;
      },
    },
  }
);

export default mongoose.model('CalcomSettings', calcomSettingsSchema, 'calcom_settings');